
spring:
  data:
    mongodb:
      #uri: #启动时从配置中心读取
      host:  #启动时从配置中心读取
      port: #启动时从配置中心读取
      database: #启动时从配置中心读取
      auto-index-creation: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: #启动时从配置中心读取
    username: #启动时从配置中心读取
    password: #启动时从配置中心读取

# 解决这个错误：org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper';
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: #启动时从配置中心读取
    port: #启动时从配置中心读取
    username: #启动时从配置中心读取
    password: #启动时从配置中心读取
    pool:
      max-active: 100
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8
      min-idle: 0
    timeout: 1200


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自定义配置
custom:
  snow-flake:
    worker-datacenter-config: #启动时从配置中心读取
  thread-pool:
    max-pool-size: 100
    keep-alive-time: 1000
    queue-size: 200
  msg-ttl-in-redis: 604800 #7天
  msg-capacity-in-redis: 1000000
  msg-read-count: 100

logging:
  config: classpath:logback-spring.xml