
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: #启动时从配置中心读取
    username: #启动时从配置中心读取
    password: #启动时从配置中心读取

  servlet:
    multipart:
      max-file-size: 50MB #设置上传文件的最大大小，默认为 1MB
      max-request-size: 50MB #设置请求中最大允许的文件大小，默认为 10MB

# 解决这个错误：org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper';
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: #启动时从配置中心读取
    port: #启动时从配置中心读取
    username: #启动时从配置中心读取
    password: #启动时从配置中心读取
    pool:
      max-active: 100
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8
      min-idle: 0
    timeout: 1200

mybatis-plus:
  configuration:
    # 输出sql日志，生产环境要使用 org.apache.ibatis.logging.nologging.NoLoggingImpl 关闭日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

obs:
  source: #启动时从配置中心读取
  image:
    max-limit: 10 #单位M
    thumb-size: 102400  #单位B
  audio:
    max-limit: 10 #单位M
  video:
    max-limit: 10 #单位M
  document:
    max-limit: 10 #单位M
  ttl: 15 #单位天
  url-expire: 86400 #单位s

  minio:
    endpoint: #启动时从配置中心读取
    endpoint-internal: #启动时从配置中心读取
    bucket-ttl: #启动时从配置中心读取
    bucket-long: #启动时从配置中心读取
    username: #启动时从配置中心读取
    password: #启动时从配置中心读取
    pre-sign: #启动时从配置中心读取

  alioss:
    endpoint: #启动时从配置中心读取
    endpoint-internal: #启动时从配置中心读取
    region: #启动时从配置中心读取
    bucket-ttl: #启动时从配置中心读取
    bucket-long: #启动时从配置中心读取
    pre-sign: #启动时从配置中心读取

#自定义配置
custom:
  snow-flake:
    worker-datacenter-config: #启动时从配置中心读取

logging:
  config: classpath:logback-spring.xml
  level:
    root: #启动时从配置中心读取