spring:
  datasource:
    url: jdbc:mysql://172.18.1.3:3306/anylink?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  redis:
    host: 172.18.1.2
    port: 6379
    password:

obs:
  type: minio
  minio:
    endpoint: http://127.0.0.1:9000
    endpoint-internal: http://172.18.1.5:9000
    bucket: anylink
    username: admin
    password: 12345678
    
  alioss:
    endpoint: blank
    endpoint-internal: blank
    region: blank
    bucket: blank

custom:
  snow-flake:
    worker-datacenter-config: 
      |-
        {
          "172.18.0.104:8040": {
            "worker-id": 0,
            "datacenter-id": 0
          },
          "172.18.0.104:8041": {
            "worker-id": 1,
            "datacenter-id": 0
          }
        }
        
logging:
  level:
    root: info
    