// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto
// Protobuf Java Version: 4.26.1

package com.hibob.anylink.common.protobuf;

public final class MsgOuterClass {
  private MsgOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      MsgOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anylink_common_protobuf_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anylink_common_protobuf_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anylink_common_protobuf_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anylink_common_protobuf_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anylink_common_protobuf_Body_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anylink_common_protobuf_Body_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anylink_common_protobuf_Extension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anylink_common_protobuf_Extension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hibob_anylink_common_protobuf_Extension_ExtensionMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hibob_anylink_common_protobuf_Extension_ExtensionMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022!com.hibob.anylink.common.pr" +
      "otobuf\"\313\001\n\003Msg\0229\n\006header\030\001 \001(\0132).com.hib" +
      "ob.anylink.common.protobuf.Header\0225\n\004bod" +
      "y\030\002 \001(\0132\'.com.hibob.anylink.common.proto" +
      "buf.Body\022D\n\textension\030c \001(\0132,.com.hibob." +
      "anylink.common.protobuf.ExtensionH\000\210\001\001B\014" +
      "\n\n_extension\"z\n\006Header\022\r\n\005magic\030\001 \001(\005\022\017\n" +
      "\007version\030\002 \001(\005\022;\n\007msgType\030\003 \001(\0162*.com.hi" +
      "bob.anylink.common.protobuf.MsgType\022\023\n\013i" +
      "sExtension\030\004 \001(\010\"\260\002\n\004Body\022\023\n\006fromId\030\001 \001(" +
      "\tH\000\210\001\001\022\027\n\nfromClient\030\002 \001(\tH\001\210\001\001\022\021\n\004toId\030" +
      "\003 \001(\tH\002\210\001\001\022\025\n\010toClient\030\004 \001(\tH\003\210\001\001\022\024\n\007gro" +
      "upId\030\005 \001(\tH\004\210\001\001\022\022\n\005msgId\030\006 \001(\003H\005\210\001\001\022\024\n\007c" +
      "ontent\030\007 \001(\tH\006\210\001\001\022\020\n\003seq\030\010 \001(\tH\007\210\001\001\022\026\n\ts" +
      "essionId\030\t \001(\tH\010\210\001\001B\t\n\007_fromIdB\r\n\013_fromC" +
      "lientB\007\n\005_toIdB\013\n\t_toClientB\n\n\010_groupIdB" +
      "\010\n\006_msgIdB\n\n\010_contentB\006\n\004_seqB\014\n\n_sessio" +
      "nId\"\226\001\n\tExtension\022T\n\014extensionMap\030\001 \003(\0132" +
      ">.com.hibob.anylink.common.protobuf.Exte" +
      "nsion.ExtensionMapEntry\0323\n\021ExtensionMapE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*\233\006\n" +
      "\007MsgType\022\t\n\005HELLO\020\000\022\016\n\nHEART_BEAT\020\001\022\010\n\004C" +
      "HAT\020\002\022\016\n\nGROUP_CHAT\020\003\022\r\n\tCHAT_READ\020\004\022\023\n\017" +
      "GROUP_CHAT_READ\020\005\022\r\n\tDELIVERED\020\006\022\013\n\007RESE" +
      "RVE\020\007\022\016\n\nSTATUS_REQ\020\010\022\016\n\nSTATUS_RES\020\t\022\017\n" +
      "\013STATUS_SYNC\020\n\022\006\n\002AT\020\013\022\n\n\006REVOKE\020\014\022\n\n\006DE" +
      "LETE\020\r\022\024\n\020SYS_GROUP_CREATE\020\025\022\030\n\024SYS_GROU" +
      "P_ADD_MEMBER\020\026\022\030\n\024SYS_GROUP_DEL_MEMBER\020\027" +
      "\022\027\n\023SYS_GROUP_SET_ADMIN\020\030\022\032\n\026SYS_GROUP_C" +
      "ANCEL_ADMIN\020\031\022\033\n\027SYS_GROUP_SET_ALL_MUTED" +
      "\020\032\022\036\n\032SYS_GROUP_CANCEL_ALL_MUTED\020\033\022\037\n\033SY" +
      "S_GROUP_SET_JOIN_APPROVAL\020\034\022\"\n\036SYS_GROUP" +
      "_CANCEL_JOIN_APPROVAL\020\035\022 \n\034SYS_GROUP_SET" +
      "_HISTORY_BROWSE\020\036\022#\n\037SYS_GROUP_CANCEL_HI" +
      "STORY_BROWSE\020\037\022\034\n\030SYS_GROUP_OWNER_TRANSF" +
      "ER\020 \022!\n\035SYS_GROUP_UPDATE_MEMBER_MUTED\020!\022" +
      "\023\n\017SYS_GROUP_LEAVE\020\"\022\022\n\016SYS_GROUP_DROP\020#" +
      "\022!\n\035SYS_GROUP_UPDATE_ANNOUNCEMENT\020$\022\031\n\025S" +
      "YS_GROUP_UPDATE_NAME\020%\022\033\n\027SYS_GROUP_UPDA" +
      "TE_AVATAR\020&\022\026\n\022CLOSE_BY_READ_IDLE\0202\022\030\n\024C" +
      "LOSE_BY_ERROR_MAGIC\0203\022\013\n\007DEFAULT\020cB%\n!co" +
      "m.hibob.anylink.common.protobufP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hibob_anylink_common_protobuf_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hibob_anylink_common_protobuf_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anylink_common_protobuf_Msg_descriptor,
        new java.lang.String[] { "Header", "Body", "Extension", });
    internal_static_com_hibob_anylink_common_protobuf_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hibob_anylink_common_protobuf_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anylink_common_protobuf_Header_descriptor,
        new java.lang.String[] { "Magic", "Version", "MsgType", "IsExtension", });
    internal_static_com_hibob_anylink_common_protobuf_Body_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hibob_anylink_common_protobuf_Body_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anylink_common_protobuf_Body_descriptor,
        new java.lang.String[] { "FromId", "FromClient", "ToId", "ToClient", "GroupId", "MsgId", "Content", "Seq", "SessionId", });
    internal_static_com_hibob_anylink_common_protobuf_Extension_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hibob_anylink_common_protobuf_Extension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anylink_common_protobuf_Extension_descriptor,
        new java.lang.String[] { "ExtensionMap", });
    internal_static_com_hibob_anylink_common_protobuf_Extension_ExtensionMapEntry_descriptor =
      internal_static_com_hibob_anylink_common_protobuf_Extension_descriptor.getNestedTypes().get(0);
    internal_static_com_hibob_anylink_common_protobuf_Extension_ExtensionMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hibob_anylink_common_protobuf_Extension_ExtensionMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
